import { useEffect, useState } from "react";
import { api, type DocumentFilters, type DocumentSummary } from "../api";
import { formatYen } from "../../domain/money";
import { TYPE_LABELS } from "../shell";

const statusLabels:Record<string,string>={DRAFT:"下書き",ISSUED:"発行済み",UNPAID:"未入金",PARTIALLY_PAID:"一部入金",PAID:"入金済",OVERDUE:"期限超過"};

export function Documents({documents,selectedType,query,setQuery,filters,setFilter,navigate}:{documents:DocumentSummary[];selectedType:string;query:string;setQuery:(v:string)=>void;filters:DocumentFilters;setFilter:(key:keyof DocumentFilters,value:string)=>void;navigate:(p:string)=>void}){
  const [showFilters,setShowFilters]=useState(false);
  const [counterparties,setCounterparties]=useState<Array<{id:string;name:string}>>([]);
  useEffect(()=>{api.counterparties().then(setCounterparties).catch(()=>setCounterparties([]))},[]);
  const list=selectedType?documents.filter(doc=>doc.type===selectedType):documents;
  const activeFilterCount=Object.values(filters).filter(Boolean).length;
  return <><div className="page-heading"><div><span className="eyebrow">DOCUMENTS　/　帳票管理</span><h1>{selectedType?TYPE_LABELS[selectedType]:"帳票"}</h1><p>作成した見積書・請求書などをまとめて管理します。</p></div><button className="button primary" onClick={()=>navigate(`/documents/new?type=${selectedType||"QT"}`)}>＋ 帳票を作成</button></div>
    <div className="list-toolbar"><div className="search-field"><span>⌕</span><input aria-label="帳票を検索" placeholder="番号・取引先・件名で検索" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><div className="filter-pills"><button className={!selectedType?"selected":""} onClick={()=>navigate("/documents")}>すべて</button>{["QT","DN","INV","RC","PO","OC"].map(t=><button key={t} className={selectedType===t?"selected":""} onClick={()=>navigate(`/documents?type=${t}`)}>{TYPE_LABELS[t]}</button>)}</div><button className={`button secondary filter-toggle ${showFilters?"active":""}`} onClick={()=>setShowFilters(v=>!v)}>絞り込み{activeFilterCount?` (${activeFilterCount})`:""}</button></div>
    {showFilters&&<section className="panel advanced-filters"><label className="field"><span>状態</span><select value={filters.status} onChange={e=>setFilter("status",e.target.value)}><option value="">すべて</option><option value="DRAFT">下書き</option><option value="ISSUED">発行済み</option><option value="UNPAID">未入金</option><option value="PARTIALLY_PAID">一部入金</option><option value="PAID">入金済</option><option value="OVERDUE">期限超過</option></select></label><label className="field"><span>取引先</span><select value={filters.counterpartyId} onChange={e=>setFilter("counterpartyId",e.target.value)}><option value="">すべて</option>{counterparties.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="field"><span>発行日（開始）</span><input type="date" value={filters.from} onChange={e=>setFilter("from",e.target.value)}/></label><label className="field"><span>発行日（終了）</span><input type="date" value={filters.to} onChange={e=>setFilter("to",e.target.value)}/></label><label className="field"><span>金額（最小）</span><input inputMode="numeric" value={filters.minAmount} onChange={e=>setFilter("minAmount",e.target.value.replace(/[^0-9]/g,""))} placeholder="0"/></label><label className="field"><span>金額（最大）</span><input inputMode="numeric" value={filters.maxAmount} onChange={e=>setFilter("maxAmount",e.target.value.replace(/[^0-9]/g,""))} placeholder="上限なし"/></label><button className="text-button clear-filters" onClick={()=>Object.keys(filters).forEach(key=>setFilter(key as keyof DocumentFilters,""))}>条件をクリア</button></section>}
    <section className="panel documents-panel">{list.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>帳票番号</th><th>帳票種別</th><th>件名</th><th>取引先</th><th>日付</th><th className="right">金額</th><th>状態</th><th/></tr></thead><tbody>{list.map(d=><tr key={d.id} onClick={()=>navigate(`/documents/${d.id}/edit`)}><td className="mono">{d.number??<span className="muted">未採番</span>}{d.revision>0&&<small className="revision-mark">改訂{d.revision}</small>}</td><td><span className={`type-badge type-${d.type.toLowerCase()}`}>{TYPE_LABELS[d.type]}</span></td><td>{d.subject||"—"}</td><td>{d.recipient_search_name||"—"}</td><td>{d.issue_date}</td><td className="amount-cell right">{formatYen(d.total_yen)}</td><td><span className={`status-tag ${d.state==="DRAFT"?"draft":d.payment_status?`payment-${d.payment_status.toLowerCase()}`:"issued"}`}>{statusLabels[d.payment_status??d.state]??d.state}</span>{d.overdue===1&&<small className="overdue-mark">期限超過</small>}</td><td className="row-arrow">→</td></tr>)}</tbody></table></div>:<div className="empty-state"><span className="empty-document">⌕</span><strong>帳票が見つかりません</strong><p>検索条件を変えるか、新しい帳票を作成してください。</p><button className="button secondary" onClick={()=>navigate(`/documents/new?type=${selectedType||"QT"}`)}>帳票を作成　→</button></div>}</section>
    <div className="list-footnote">帳票の検索結果 <strong>{list.length}</strong> 件 <span>・　最新の帳票を上に表示しています</span></div>
  </>;
}
