import { useEffect, useRef, useState } from "react";
import { api } from "../api";

type Kind="counterparties"|"products";
export function Masters({kind}:{kind:Kind}){
 const [rows,setRows]=useState<Array<Record<string,unknown>>>([]);const [error,setError]=useState("");const [saved,setSaved]=useState("");const [query,setQuery]=useState("");const [showForm,setShowForm]=useState(false);
 const [nextCursor,setNextCursor]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [activeQuery,setActiveQuery]=useState("");const generation=useRef(0);
 async function load(q=query,cursor?:string){
   const ticket=cursor?generation.current:++generation.current;setBusy(true);setError("");
   try{const page=kind==="counterparties"?await api.counterpartiesPage(q,"all",cursor):await api.productsPage(q,cursor);if(ticket!==generation.current)return;
     const incoming=page.data as unknown as Array<Record<string,unknown>>;setRows(old=>cursor?[...old,...incoming]:incoming);setNextCursor(page.nextCursor);setActiveQuery(q);
   }catch(e){if(ticket===generation.current)setError(e instanceof Error?e.message:"読み込めませんでした")}finally{if(ticket===generation.current)setBusy(false)}
 }
 useEffect(()=>{setRows([]);setQuery("");setNextCursor(null);void load("");return()=>{generation.current++}},[kind]);
 async function submit(form:HTMLFormElement){const fd=new FormData(form);const v=(key:string)=>String(fd.get(key)??"");try{if(kind==="counterparties")await api.addCounterparty({name:v("name"),kana:v("kana"),isCustomer:fd.has("customer"),isSupplier:fd.has("supplier"),postalCode:v("postal"),prefecture:v("prefecture"),address:v("address"),phone:v("phone"),email:v("email"),notes:v("notes")});else await api.addProduct({code:v("code"),name:v("name"),description:v("description"),unit:v("unit"),unitPrice:v("price"),taxClass:v("taxClass")});form.reset();setShowForm(false);setSaved("登録しました。");void load("");window.setTimeout(()=>setSaved(""),3000)}catch(e){setError(e instanceof Error?e.message:"登録できませんでした")}}
 const counterparty=kind==="counterparties";return <><div className="page-heading"><div><span className="eyebrow">MASTER DATA　/　{counterparty?"PARTNERS":"PRODUCTS"}</span><h1>{counterparty?"取引先":"商品・サービス"}</h1><p>{counterparty?"お客様・仕入先の情報をまとめて管理します。":"よく使う品名や価格を帳票の明細に再利用できます。"}</p></div><button className="button primary" onClick={()=>{setShowForm(!showForm);setError("")}}>＋ {counterparty?"取引先を追加":"商品を追加"}</button></div>
 {showForm&&<section className="panel master-form-panel"><div className="section-heading"><div><h2>{counterparty?"取引先情報":"商品・サービス情報"}</h2><span>入力した情報は次回の帳票作成時に使用できます。</span></div><button className="icon-button" onClick={()=>setShowForm(false)}>×</button></div><form onSubmit={e=>{e.preventDefault();void submit(e.currentTarget)}}><div className="field-grid">{counterparty?<><label className="field"><span>会社名 <b>*</b></span><input name="name" required maxLength={200} placeholder="株式会社ABC"/></label><label className="field"><span>会社名かな</span><input name="kana" maxLength={200}/></label><label className="field"><span>郵便番号</span><input name="postal" placeholder="100-0001"/></label><label className="field"><span>都道府県</span><input name="prefecture" placeholder="東京都"/></label><label className="field full"><span>住所</span><input name="address"/></label><label className="field"><span>電話番号</span><input name="phone"/></label><label className="field"><span>メール</span><input name="email" type="email"/></label><fieldset className="field full"><legend>取引区分</legend><label className="checkbox-label"><input type="checkbox" name="customer" defaultChecked/> 得意先</label><label className="checkbox-label"><input type="checkbox" name="supplier"/> 仕入先</label></fieldset><label className="field full"><span>メモ</span><textarea name="notes" rows={2}/></label></>:<><label className="field"><span>商品コード <b>*</b></span><input name="code" required maxLength={40}/></label><label className="field"><span>品名 <b>*</b></span><input name="name" required maxLength={200}/></label><label className="field full"><span>説明</span><input name="description"/></label><label className="field"><span>単位</span><input name="unit" defaultValue="個" required/></label><label className="field"><span>標準単価（円）</span><input name="price" inputMode="decimal" defaultValue="0" required/></label><label className="field"><span>税区分</span><select name="taxClass" defaultValue="STANDARD_10"><option value="STANDARD_10">10%</option><option value="REDUCED_8">8% 軽減</option><option value="NON_TAXABLE">非課税</option><option value="OUT_OF_SCOPE">不課税</option><option value="EXEMPT">免税</option></select></label></>}</div><div className="editor-bottom-actions"><button type="button" className="button secondary" onClick={()=>setShowForm(false)}>キャンセル</button><button className="button primary">登録する</button></div></form></section>}
 <div className="list-toolbar"><div className="search-field"><span>⌕</span><input placeholder={counterparty?"会社名・かなで検索":"品名・商品コードで検索"} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load(query)}}/><button className="text-button" onClick={()=>void load(query)}>検索</button></div><span className="master-count">{rows.length} 件</span></div>
 {error&&<div role="alert" className="inline-alert">{error}<button onClick={()=>setError("")}>　×</button></div>}{saved&&<div className="inline-success">{saved}</div>}
 <section className="panel documents-panel">{rows.length?<div className="table-wrap"><table className="data-table"><thead><tr>{counterparty?<><th>会社名</th><th>取引区分</th><th>住所</th><th>電話番号</th></>:<><th>商品コード</th><th>品名</th><th>単位</th><th>標準単価</th><th>税区分</th></>}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id??index)}>{counterparty?<><td><strong>{String(row.name)}</strong></td><td>{row.is_customer?"得意先":""}{row.is_customer&&row.is_supplier?"・":""}{row.is_supplier?"仕入先":""}</td><td>{String(row.address||"—")}</td><td>{String(row.phone||"—")}</td></>:<><td className="mono">{String(row.code)}</td><td><strong>{String(row.name)}</strong></td><td>{String(row.unit)}</td><td className="amount-cell">¥{new Intl.NumberFormat("ja-JP").format(Number(row.unit_price_decimal))}</td><td>{String(row.tax_class)==="STANDARD_10"?"10%":String(row.tax_class)==="REDUCED_8"?"8%":"非課税"}</td></>}</tr>)}</tbody></table></div>:<div className="empty-state"><span className="empty-document">◇</span><strong>{counterparty?"取引先を登録してください":"商品・サービスを登録してください"}</strong><p>情報を登録すると、帳票作成時に再利用できます。</p><button className="button secondary" onClick={()=>setShowForm(true)}>＋ {counterparty?"取引先を追加":"商品を追加"}</button></div>}</section>{nextCursor&&<button className="button secondary" disabled={busy} onClick={()=>void load(activeQuery,nextCursor)}>{busy?"読み込み中…":"さらに表示"}</button>}</>;
}
