import { useEffect, useState } from "react";
import { api } from "../api";
import { formatYen } from "../../domain/money";

const currentMonth=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit"}).format(new Date());
export function Sales(){
  const [month,setMonth]=useState(currentMonth());
  const [data,setData]=useState<Awaited<ReturnType<typeof api.sales>>|null>(null);
  const [trend,setTrend]=useState<Array<{month:string;salesYen:number}>>([]);
  const [partners,setPartners]=useState<Array<{counterparty_name:string;invoice_count:number;sales_yen:number;invoiced_yen:number}>>([]);
  const [overdue,setOverdue]=useState<Awaited<ReturnType<typeof api.overdueInvoices>>>([]);
  const [error,setError]=useState("");
  useEffect(()=>{api.sales(month).then(setData).catch(e=>setError(e.message));api.monthlySales(month,6).then(setTrend).catch(()=>setTrend([]));api.salesByCounterparty(month).then(setPartners).catch(()=>setPartners([]));api.overdueInvoices().then(setOverdue).catch(()=>setOverdue([]))},[month]);
  const maxSales=Math.max(1,...trend.map(item=>item.salesYen));const chartMax=Math.max(100_000,Math.ceil(maxSales/100_000)*100_000);
  return <><div className="page-heading"><div><span className="eyebrow">SALES　/　売上・入金</span><h1>売上管理</h1><p>請求書をもとに、売上と入金の状況を確認できます。</p></div><label className="month-picker"><span>対象月</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>{error&&<div className="inline-alert">{error}</div>}
    <div className="definition-note"><span>i</span><div><strong>売上高の定義</strong><p>売上高は、請求日を基準とした発行済み請求書の税抜合計です。会計上の売上計上とは異なります。</p></div></div>
    <div className="metric-grid sales-metrics"><Metric label="売上高" value={formatYen(data?.salesYen??0)} sub="発行済み請求書の税抜合計" icon="↗" color="blue"/><Metric label="請求済" value={formatYen(data?.invoicedYen??0)} sub="対象月に発行した請求書" icon="▤" color="violet"/><Metric label="入金済" value={formatYen(data?.paidYen??0)} sub="対象月の請求に対する現在の入金" icon="✓" color="green"/><Metric label="未入金" value={formatYen(data?.outstandingYen??0)} sub="請求済金額から入金済金額を差し引いた残高" icon="◷" color="amber"/></div>
    <div className="dashboard-grid sales-grid"><section className="panel trend-panel"><div className="section-heading"><div><h2>月別売上</h2><span>請求書発行月ごとの税抜売上</span></div><span className="chart-legend"><i/>売上高</span></div><div className="chart-area sales-chart"><div className="chart-y"><span>{formatYen(chartMax)}</span><span>{formatYen(chartMax/2)}</span><span>¥0</span></div><div className="chart-grid"><div className="chart-line"/><div className="chart-line"/><div className="chart-line"/><div className="bars">{trend.map((item,index)=><div className="bar-column" key={item.month}><div className={`bar ${index===trend.length-1?"bar-current":""}`} style={{height:`${item.salesYen?Math.max(3,item.salesYen/chartMax*88):1}%`}}/><span>{Number(item.month.slice(5))}月</span></div>)}</div></div></div></section><section className="panel overdue-panel"><div className="section-heading"><div><h2>期限超過</h2><span>支払期限を過ぎた未入金</span></div><span className="count-pill">{overdue.length} 件</span></div>{overdue.length?<div className="overdue-list">{overdue.slice(0,5).map(item=><div className="overdue-row" key={item.id}><span><strong>{item.recipient_search_name}</strong><small>{item.number}　期限 {item.due_date}</small></span><b>{formatYen(item.outstanding_yen)}</b></div>)}</div>:<div className="empty-state compact"><span className="empty-check">✓</span><strong>期限を過ぎた請求書はありません</strong><p>請求書の支払期限と入金状況から自動で判定します。</p></div>}</section></div>
    <section className="panel partner-sales-panel"><div className="section-heading"><div><h2>取引先別売上</h2><span>{month.replace("-","年")}月に発行した請求書</span></div></div>{partners.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>取引先</th><th>請求書数</th><th className="right">売上高（税抜）</th><th className="right">請求済（金額）</th></tr></thead><tbody>{partners.map((row,index)=><tr key={`${row.counterparty_name}-${index}`}><td>{row.counterparty_name}</td><td>{row.invoice_count} 件</td><td className="amount-cell right">{formatYen(row.sales_yen)}</td><td className="amount-cell right">{formatYen(row.invoiced_yen)}</td></tr>)}</tbody></table></div>:<div className="empty-state compact"><span className="empty-document">↗</span><strong>対象月の売上データはありません</strong><p>請求書を発行すると、取引先ごとの売上が表示されます。</p></div>}</section>
    <div className="sales-note">入金済は対象月の請求書に対する、現在までの入金額です。入金日ごとの集計とは異なります。</div>
  </>;
}
function Metric({label,value,sub,icon,color}:{label:string;value:string;sub:string;icon:string;color:string}){return <article className="metric-card"><div className="metric-top"><span>{label}</span><span className={`metric-icon ${color}`}>{icon}</span></div><strong>{value}</strong><small>{sub}</small><span className={`metric-accent ${color}`}/></article>}
