import { useEffect, useState } from "react";
import type { Organization } from "../api";
import { api } from "../api";

export function Settings({organization,saved}:{organization:Organization|null;saved:()=>void}){
 const [form,setForm]=useState({legal_name:"",display_name:"",postal_code:"",prefecture:"",address:"",building:"",phone:"",representative:"",registration_number:"",qualified_mode:false,theme:"standard" as "standard"|"modern",accent_color:"#315b78"});const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{if(organization)setForm({legal_name:organization.legal_name,display_name:organization.display_name,postal_code:organization.postal_code,prefecture:organization.prefecture,address:organization.address,building:organization.building,phone:organization.phone,representative:organization.representative,registration_number:organization.registration_number??"",qualified_mode:Boolean(organization.qualified_mode),theme:organization.theme,accent_color:organization.accent_color})},[organization]);
 function change(key:keyof typeof form,value:string|boolean){setForm(old=>({...old,[key]:value}))}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{await api.saveOrganization(form);saved()}catch(error){setMessage(error instanceof Error?error.message:"保存できませんでした")}finally{setBusy(false)}}
 return <><div className="page-heading"><div><span className="eyebrow">SETTINGS　/　ORGANIZATION</span><h1>設定</h1><p>会社情報や帳票の表示を設定します。</p></div></div><div className="settings-layout"><nav className="settings-nav"><button className="selected">▣　会社情報</button><button disabled>▧　帳票・採番</button><button disabled>₮　振込先</button><button disabled>◉　ユーザー</button><small>各設定項目は順次ご利用いただけます。</small></nav><form className="panel settings-panel" onSubmit={submit}><div className="section-heading"><div><h2>会社情報</h2><span>帳票に表示する発行元の情報です。</span></div></div><div className="field-grid"><label className="field"><span>会社名（正式名称） <b>*</b></span><input required value={form.legal_name} onChange={e=>change("legal_name",e.target.value)}/></label><label className="field"><span>表示名 <b>*</b></span><input required value={form.display_name} onChange={e=>change("display_name",e.target.value)}/></label><label className="field"><span>郵便番号</span><input value={form.postal_code} onChange={e=>change("postal_code",e.target.value)}/></label><label className="field"><span>都道府県</span><input value={form.prefecture} onChange={e=>change("prefecture",e.target.value)}/></label><label className="field full"><span>住所</span><input value={form.address} onChange={e=>change("address",e.target.value)}/></label><label className="field full"><span>建物名</span><input value={form.building} onChange={e=>change("building",e.target.value)}/></label><label className="field"><span>電話番号</span><input value={form.phone} onChange={e=>change("phone",e.target.value)}/></label><label className="field"><span>代表者</span><input value={form.representative} onChange={e=>change("representative",e.target.value)}/></label></div>
 <div className="settings-divider"/><div className="form-section-title settings-subtitle"><span className="form-step">02</span><div><h2>インボイス・デザイン</h2><p>適格請求書発行事業者の情報と帳票のテーマを設定します。</p></div></div><div className="field-grid"><label className="field"><span>登録番号</span><input value={form.registration_number} placeholder="T1234567890123" onChange={e=>change("registration_number",e.target.value)}/></label><label className="checkbox-row"><input type="checkbox" checked={form.qualified_mode} onChange={e=>change("qualified_mode",e.target.checked)}/><span><strong>適格請求書発行事業者として発行</strong><small>有効な登録番号が必要です。</small></span></label><label className="field"><span>帳票テーマ</span><select value={form.theme} onChange={e=>change("theme",e.target.value)}><option value="standard">STANDARD　モノクロ</option><option value="modern">MODERN　アクセントカラー</option></select></label><label className="field"><span>アクセントカラー</span><div className="color-field"><input type="color" value={form.accent_color} onChange={e=>change("accent_color",e.target.value)}/><code>{form.accent_color}</code></div></label></div>
 {message&&<div className="inline-alert">{message}</div>}<div className="settings-footer"><span>変更内容は次回作成する帳票から反映されます。</span><button className="button primary" disabled={busy}>{busy?"保存中…":"変更を保存"}</button></div></form></div></>;
}
